name: lint-check
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install next
      - name: Debug Info
        run: |
          echo "Node Version: $(node --version)"
          echo "Prettier Version: $(npx prettier --version)"
          echo "Prettier Config: $(cat .prettierrc)"
          echo "GitHub Actions Environment: ${{ toJson(env) }}"
      - run: npm run lint:check
      - run: npm run format
      - run: cat tsconfig.json
      - run: git diff tsconfig.json
      - run: npm run format:check
